apiVersion: apps/v1
kind: Deployment
metadata:
   name: apigateway
spec:
   selector:
      matchLabels: 
         app: apigateway
   replicas: 1
   template:
      metadata:
         labels:
            app: apigateway
      spec:
         containers:
            - name: apigateway-container
              image: shahnawaz786/apigateway
              imagePullPolicy: IfNotPresent
              ports:
                 - containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
   name: apigatewaysvc
spec:
   selector:
      app: apigateway
   ports:
      - port: 80
        targetPort: 9003
        protocol: "TCP"
   type: LoadBalancer