server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME:default}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:default}