apiVersion: apps/v1
kind: Deployment
metadata:
   name: user-service
spec:
   selector:
      matchLabels: 
         app: user-service
   replicas: 1
   template:
      metadata:
         labels:
            app: user-service
      spec:
         containers:
            - name: user-service-container
              image: shahnawaz786/user-service
              imagePullPolicy: IfNotPresent
              ports:
                 - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
   name: user-servicesvc
spec:
   selector:
      app: user-service
   ports:
      - port: 80
        targetPort: 9001
   type: ClusterIP